name: Build on macOS (Clang)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
        mkdir build
        cd build
        cmake ..
        make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
